version: '3.9'

volumes:
  html:
  dbfile:

networks:
  app:
    driver: bridge

services:

  phpmyadmin:
    image: phpmyadmin:5.2
    # restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
      POST_MAX_SIZE: 1024M
      UPLOAD_MAX_FILESIZE: 1024M
    depends_on:
      - db
    networks:
      - app


  db:
    image: mysql:8.0
    # restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wp_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - dbfile:/var/lib/mysql
      - ./.configuration/mysql/my.cnf:/etc/my.cnf #for shrink RAM
    networks:
      - app

  server:
    container_name: wp-apache
    build:
      context: ./.configuration
    volumes:
      - ./html/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./html/wp-content/themes/logotype-ssr:/var/www/html/wp-content/themes/logotype-ssr
      - ./html/wp-content/uploads:/var/www/html/wp-content/uploads

      - ./.configuration/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./html/wp-config.php:/var/www/html/wp-config.php
      - ./html/.htaccess:/var/www/html/.htaccess

      - ./html/wp-content/debug.log:/var/www/html/wp-content/debug.log
    ports:
      - 80:80
    depends_on:
      - db
    # restart: unless-stopped
    networks:
      - app
  
  nodejs: 
    container_name: nodejs
    image: node:latest



# html/wp-content/themes/logotype-ssr/vue-vite-ssr