version: '3.9'

volumes:
  html:
  dbfile:

networks:
  app:
    driver: bridge

services:

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: docker-phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
      POST_MAX_SIZE: 1024M
      UPLOAD_MAX_FILESIZE: 1024M
    depends_on:
      - db
    networks:
      - app


  db:
    image: mysql:8.0
    container_name: docker-db
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wp_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - dbfile:/var/lib/mysql
      - ./configuration/db/mysql/my.cnf:/etc/my.cnf #for shrink RAM
    networks:
      - app

  server:
    container_name: wc-docker-server
    build:
      context: ./configuration/server
    volumes:
      - ./html/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./html/wp-content/themes/logotype-ssg:/var/www/html/wp-content/themes/logotype-ssg
      - ./html/wp-content/uploads:/var/www/html/wp-content/uploads


      - ./configuration/server/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./html/wp-config.php:/var/www/html/wp-config.php
      - ./html/.htaccess:/var/www/html/.htaccess

    env_file:
      ./configuration/server/.env
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - app
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  # host-gateway(default) - 172.17.0.1  

  # LOCAL ONLI, FUCK IT \/
  # node: 
  #   container_name: docker-node
  #   build:
  #     context: ./html/wp-content/themes/logotype-ssg/vue-vite-ssg
  #   ports:
  #     - "3000:3000"
    
  #   volumes:
  #     - ./html/wp-content/themes/logotype-ssg/vue-vite-ssg:/usr/src/app
  #     - /usr/src/app/node_modules
  #     # - ./home/artbot/dev/wp-docker-apache/html/wp-content/themes/logotype-ssg/vue-vite-ssg:/usr/src/app
  #   # command: npm install
  #     # - npm install
  #     # - npm run dev

      